server:
  port: 8080

spring:
  application:
    name: delivery application

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: secret
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        max.block.ms: 5000